### PR TITLE
Support Swift Package Manager based project for macOS

### PR DESCRIPTION
**Pull request by kitasuke**
## Description

Rough idea to detect `Package.swift` to support SPM

See more details in this issue: https://github.com/bitrise-core/bitrise-init/issues/142

### CODE REVIEW

**Comment by godrei** [comment]
Hi @kitasuke , may I ask you to create a feature request on [discuss](https://discuss.bitrise.io/c/feature-request) for this PR  draft? On discuss it can get more visibility, others can vote on it and we process the feature requests in order of popularity.

If you would like to develop this feature, I would ask you to separate this feature into a new scanner type, as swift package manager based CLI tools are treated differently as Xcode based macOS project. 

Like it seems to manage dependencies you need to use `swift` instead of `carthage` or `cocoapods`. To build the final binary you need to use `swift` instead of `xcodebuild`.

We have a guide about how to create your own scanner on the devcenter: https://devcenter.bitrise.io/bitrise-cli/creating-your-own-bitrise-project-scanner/

**Comment by kitasuke** [comment]
Thank you for your feedback! Didn't know the place, I should've created a request there... Will do this later.

Agreed with your suggestion. Well, I just wanted to bring up this topic and discuss first. Anyway, I would like to develop this feature because it looks fun. I'll follow the guide.

I'll close this PR once I created a feature request.

**Comment by godrei** [comment]
Hi @kitasuke ,
what is the progress with this feature request? Do you need this draft to be open?

**Comment by kitasuke** [comment]
Haven't started yet. I'll close now since the approach would be different from this PR.

**Pull request closed without merging**
